### ISSUE TITLE
Add TypeScript definition to conformance package ?

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/npm-tarball-license-parser#10]
It would be cool to open a pull-request to add an index.d.ts in the conformance package:
https://github.com/cutenode/conformance

This would prevent us from having it in this project.
https://github.com/NodeSecure/npm-tarball-license-parser/blob/master/index.d.ts

**Comment by Rossb0b** [comment]
https://github.com/cutenode/conformance/pull/14
https://github.com/cutenode/conformance/pull/15

NB: Le `from` est propre à l'usage fait dans npm-tarball-license-parser.

**Comment by Kawacrepe** [comment]
On dirait qu'il n'y a plus aucune activité au niveau de conformance, il serait peut être plus simple de fork / faire un projet adapté à nos besoins ?

**Comment by Kawacrepe** [comment]
On devrait publier https://github.com/NodeSecure/licenses-conformance sur npm et remplacer conformance par notre package dans npm-tarball-license-parser, ça permettrait de fermer cette issue
